apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
#git::https://github.com/example/repository/?ref=main
- git::https://github.com/emage-automation/test/00-deploying-application/?ref=main
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo
commonAnnotations:
  oncallPager: 800-555-1212
